# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20161014_2359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Images',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='image',
            new_name='images',
        ),
    ]
